name: Scheduled Data Update

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Call Render Server to Update Data
        run: |
          curl -X GET https://portfoliobackend-uwr7.onrender.com/api/trigger-update
